**Numpy** **Library**

In [1]:
 import numpy as np

Basics

In [ ]:
a = np.array([2.0,4.5,6])
print(a)

b = np.array([[2,5.6,7.8] , [3,6,8]])
print(b)

# #getting shape
b.shape

# #getting dimension
b.ndim

[2.  4.5 6. ]
[[2.  5.6 7.8]
 [3.  6.  8. ]]


2

get data type

In [ ]:
b.dtype

dtype('float64')

get size

In [ ]:
b.itemsize

8

get total size

In [ ]:
b.nbytes

48

get a specific element

In [ ]:
b[1,2]

8.0

get a specific column

In [ ]:
b[:,2]

array([7.8, 8. ])

get a specific row

In [ ]:
b[1,:]

array([3., 6., 8.])

accesing middle elements in a row

In [ ]:
c=np.array([[32,5,6,43,34,6,3,5,8,1] , [3,5,4,7,3,5,35,4,3,2]])


To change an element in array

In [ ]:
c[:,2] = 20
print(c)

c[:,2] = [2,6]
print(c)

c[1,4] = 3
print(c)

[[32  5 20 43 34  6  3  5  8  1]
 [ 3  5 20  7  3  5 35  4  3  2]]
[[32  5  2 43 34  6  3  5  8  1]
 [ 3  5  6  7  3  5 35  4  3  2]]
[[32  5  2 43 34  6  3  5  8  1]
 [ 3  5  6  7  3  5 35  4  3  2]]


Get specific element

In [ ]:
d = np.array([[[2,4,5] , [4,7,1]] , [[8,9,7,] , [1,4,8]]])
print(d)

#accesing a element
d[0,1,2] # here 0 represents 1st row then , 1 represents the 2nd sub row and 2 represents the element at 3rd position that is '1' .
d[0,:,:] # here 0 represents the 1st row then ':' reprensents the whole row and again ':' represents all elements of row

[[[2 4 5]
  [4 7 1]]

 [[8 9 7]
  [1 4 8]]]


array([[2, 4, 5],
       [4, 7, 1]])

All 0's matrix

In [ ]:
np.zeros((4,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

All 1's matrix

In [ ]:
np.ones((4,3,2,3))

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

Any other number

In [2]:
np.full((2,2) , 55)

array([[55, 55],
       [55, 55]])

Built an array in shape of other array

In [ ]:
np.full(b.shape , 6)
#   OR
np.full_like(b,6)

array([[6., 6., 6.],
       [6., 6., 6.]])

Any random number array

In [ ]:
np.random.rand(3,1)

np.random.random_sample(b.shape)

array([[0.97067214, 0.81496474, 0.17335497],
       [0.96033453, 0.67851237, 0.03422961]])

generate an integer array with some values constraints

In [ ]:
np.random.randint(-2,5 , size = (3,4))  #here -2,5 is the constraint that the number should be in between these -2 to 5.

array([[ 2,  4,  2, -1],
       [-1,  0, -1,  4],
       [ 3,  0,  2, -2]])

Identity Matrix

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Reapeat an array

In [9]:
arr = np.array([[1,4,3,6,7]])
repeat = np.repeat(arr , 3 )
print(repeat)

[1 1 1 4 4 4 3 3 3 6 6 6 7 7 7]


In [10]:
ones = np.ones((5,5))
print(ones)

zero = np.zeros((3,3))
zero[1,1] = 9
print(zero)

ones[1:4,1:4] = zero
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful with copying array

In [15]:
n = [1,3,5]
s = n #it means 's' is same as 'n' .
s[1] = 35 # it means the value will also change in 'n'
print(n)
print(s)

x = [1,2,3,4]
y = x.copy() #this actually copies data from 'x' to 'y' . Now changes in 'y' will not 'x' .
y[0] = 34

print(x)

print(y)

[1, 35, 5]
[1, 35, 5]
[1, 2, 3, 4]
[34, 2, 3, 4]


Mathematics in Array

In [33]:
w = np.array([2,4,7,9])

#add
w = w + 2
w

#subtract
w = w - 2
w

#multiply
w = w*2
w

#division
w = w/2
w

#add an array
v = np.array([2,5,7,9])
w = w+v
w

#power
w = w**3
w

#sin
np.sin(w)

#cos
np.cos(w)

array([ 0.39185723,  0.98869558, -0.18019325,  0.3585941 ])

Linear Algebra

In [35]:
p = np.ones((3,6))
q = np.full((6,2) , 4)

np.matmul(p,q)

array([[24., 24.],
       [24., 24.],
       [24., 24.]])

Find the determinant of matrix

In [37]:
e = np.full((3,3) , 4)
np.linalg.det(e)

0.0

Statistics

In [50]:
stats = np.array([[1,5,3,] , [3,7,1]])
stats

r = np.min(stats)

t = np.max(stats)
print(t)

y = np.sum(stats)
print(y)

7
20


Reorganizing Arrays

In [51]:
before = np.array([[23,56,34],[28,45,9]])
print(before)

after = before.reshape((1,6))
print(after)

[[23 56 34]
 [28 45  9]]
[[23 56 34 28 45  9]]


Vertical stacking of arrays

In [52]:
v1 = np.array([1,3,6])
v2 = np.array([6,3,8])
np.vstack([v1,v2,v2,v1,v2])

array([[1, 3, 6],
       [6, 3, 8],
       [6, 3, 8],
       [1, 3, 6],
       [6, 3, 8]])

Horizontal stacking of arrays

In [53]:
h1 = np.array([1,3,6])
h2 = np.array([6,3,8])
np.hstack([h1,h2,h2,h1,h1])

array([1, 3, 6, 6, 3, 8, 6, 3, 8, 1, 3, 6, 1, 3, 6])